# Generated by Django 4.0.6 on 2022-07-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_user_username_alter_productcategory_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='qty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
