# Generated by Django 4.0.6 on 2022-07-27 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_user_product_price_user_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubcategory',
            name='product_categoty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.productcategory'),
        ),
    ]
