# Generated by Django 4.0.6 on 2022-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_productsubcategory_product_categoty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qty',
            field=models.CharField(blank=True, default=1, max_length=255, null=True),
        ),
    ]
