# Generated by Django 4.0.6 on 2022-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_alter_user_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='product_price',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qty',
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
