# Generated by Django 4.0.6 on 2022-07-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_alter_user_locations_alter_user_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, max_length=255, null=True)),
                ('product_price', models.CharField(blank=True, max_length=300, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempBask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.IntegerField(blank=True, max_length=255, null=True)),
                ('product_price', models.CharField(blank=True, max_length=300, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='choice_price_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qty',
        ),
    ]
