# Generated by Django 4.0.6 on 2022-07-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_basket_tempbask_remove_user_choice_price_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productsubcategorydetail',
            name='sub_categoty_name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='toll_price',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tempbask',
            name='qty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='locations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
